### ISSUE TITLE
Selecting data from a table (Indexeddb) which contains a column with array data

### ISSUE THREAD

**Issue by report-zone** [AlaSQL/alasql#1253]
I had posted this same questions to stack overflow a while back, but no responses, hence nobody knows???

I have the following data (simplified):

Indexeddb table "my_aliases"
```
[
  {
    "name": "one",
    "aliases": [
      {
        "name": "one-A"
      },
      {
        "name": "one-B"
      },
      {
        "name": "one-C"
      },
      {
        "name": "one-D"
      }
    ]
  },
  {
    "name": "two",
    "aliases": [
      {
        "name": "two-A"
      },
      {
        "name": "two-B"
      }
    ]
  },
  {
    "name": "three",
    "aliases": [
      {
        "name": "three-1"
      },
      {
        "name": "three-2"
      },
      {
        "name": "three-omega"
      }
    ]
  }
]
```

I want to get

```
 name    alias-0    alias-1    alias-2     alias-3
 ============================================================================       
 one     one-A      one-B      one-C       one-D
 two     two-A      two-B
 three   three-1    three-2    three-omega
```

 Since there could be (n) alias is it possible to write this as a query?

 I tried using SEARCH but that doesn't work with IndexedDB 

 I can do THIS (see below), but I would have to know up front the max number of aliases which I don't...

```
    SELECT 
      name, 
      aliases->[0]->name, 
      aliases->[1]->name, 
      aliases->[2]->name, 
      aliases->[3]->name 
   FROM my_aliases 
    WHERE aliases.length > 0
```

Any ideas on how to solve this ?

**Comment by MianAnwar** [comment]
still getting the same response any update?

**Comment by mathiasrw** [comment]
# AlaSQL bot says

To achieve the dynamic column generation for varying numbers of aliases in AlaSQL with IndexedDB, you'll need a dynamic approach since AlaSQL does not support direct pivoting or dynamic column generation within a single query as some other SQL databases do. Here's a two-step approach using JavaScript and AlaSQL:

1. **Determine the Maximum Number of Aliases**: First, you need to find out the maximum number of aliases any entry has. This can be done with a separate query or by processing the data in JavaScript.

2. **Construct and Execute a Dynamic Query**: Based on the maximum number of aliases, you can dynamically construct a SQL query that selects each alias as a separate column.

Here's a JavaScript function that demonstrates this approach:

```javascript
async function transformData() {
  // Step 1: Find the maximum number of aliases
  let maxAliases = 0;
  const allData = await alasql('SELECT * FROM my_aliases');
  
  allData.forEach(item => {
    if (item.aliases && item.aliases.length > maxAliases) {
      maxAliases = item.aliases.length;
    }
  });

  // Step 2: Construct and execute the dynamic query
  let query = 'SELECT name';
  for (let i = 0; i < maxAliases; i++) {
    query += `, aliases->[${i}]->name AS alias-${i}`;
  }
  query += ' FROM my_aliases WHERE aliases.length > 0';

  return await alasql(query);
}

transformData().then(result => console.log(result));
```

This function first iterates through the data to find the maximum number of aliases. Then, it constructs a SQL query with the appropriate number of columns based on this maximum and executes it.

**Note**: This method assumes that the `my_aliases` data is already loaded into an IndexedDB table that AlaSQL can query.
