### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script...

### ISSUE THREAD

**Issue by madeupofstardust** [AlaSQL/alasql#1489]
Hi. I use Alasql with Teampermonkey, and in certains sites I got this error from console:

`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' '*' 'unsafe-inline' *.gstatic.com *.google.com *.googleapis.com *.bootstrapcdn.com".`

Looks like the Content Security Policy in many websites doesn't allow to use unsafe eval, so Alasql doesnt't work there. 

I tried with this cdns:

https://cdn.jsdelivr.net/alasql/latest/alasql.min.js

https://cdn.jsdelivr.net/npm/alasql

And I got the same error. Is there a way to solve this issue?

**Comment by mathiasrw** [comment]
Unsafe eval is the core of how AlaSQL is structured. 

In _theory_ you can alasql.compile what you need and extract the generated function and manage how the function gets the data it needs and then manually move the functions over and use as part of your code instead of AlaSQL, but its not a pleasant experience.

**Comment by githorse** [comment]
Dupllicates #1482.
