### ISSUE TITLE
Bug when a variable is assigned from a query

### ISSUE THREAD

**Issue by pabloBelt** [AlaSQL/alasql#1645]
Hi, 

There is a bug when a variable takes a value from a query.

`DECLARE` @X NUMBER = (SELECT MAX(population) FROM cities) `

http://jsfiddle.net/wa5hz8nd/1/

It can also be reproduced with the latest 3.0.0 version:

![image](https://user-images.githubusercontent.com/125101677/220732094-35f4d4f4-28f2-4215-9931-0aed28f40284.png)

Bests,
Pablo

**Comment by joan8ruth** [comment]
Hello @pabloBelt ,
I see that the declare could be split into two steps:

declare @V NUMBER; 
SET @V = (Select MAX(X) from T);

and is working fine this way (maybe it works only this way? because I believe this is what I usually do when writing queries), but I would like to know if the single line declaration you have mentioned was working in the previous version.

Regards,
Joanna

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue, please assign me.

**Comment by mathiasrw** [comment]
Fix Released as part of v4.0.6
