### ISSUE TITLE
Question: Should Alasql implements fluent / Linq interface and plug-ins for jQuery and d3.js?

### ISSUE THREAD

**Issue by agershun** [AlaSQL/alasql#25]
First case: There is an opinion, that JS programmers are more familiar with fuent interface (a la Linq), rather than "pure" SQL.

``` js
    var res = alasql('SELECT TOP 10 a,b FROM one GROUP BY a,b ORDER BY b');
    // replace with
    var res = alasql.select(['a','b']).top(10).from('one').groupby(['a','b']).orderby('b').exec();
```

The second case - integration with d3.js, jQuery, and other libraries: Should Alasq SQL support plug-in functions for these popular libraries?

``` js
    $("div").alasql("SELECT * FROM ? WHERE textContent LIKE "A%"");
    d3.select('body').selectAll('div')
    .alasql('SELECT * FROM XLSX("mydata.xlsx") WHERE total>10')
    .enter().append('div').text(function(d){return d.name});

Should Alasql extend API with fluent interface functions?
```

**Comment by IPWright83** [comment]
In response to the first case - should alasql support a fluent interface, it's probably a nice to have, but I would suggest anyone who has an understanding of SQL to an extent where they can use the fluent API should be able to use the string version. It might be a nice feature to add in the future when it's feature complete, but I don't think it's required now. 

Personally I only ever use the first approach (String based), because I want to dynamically construct filters which string concatenation allows but the fluent API doesn't. If I've needed to use a fluent API for any reason (I did for one section to manage multiple WHERE clauses) I've used Squel.js http://hiddentao.github.io/squel/ to produce a SQL statement used by Alasql.

As for the second case I would advocate quite strongly NO, that alasql's job is to allow the SQL functionality. If 3rd party library integration is required then these should be in separate projects, and not pollute alasql's codebase with specifics for libraries that will increase the deployment overhead and possibly lead to stale/unused code if these 3rd party libraries become less popular.

**Comment by agershun** [comment]
Thank you for the answer!

 A) I include fluent interface in next version 0.0.36. There some performance issues related to caching approach, and I will write notes about it.

B) for external libraries: I will include native support only for Angular.js (because of popularity of this library), but not for d3.js. I am thinking about plug-ins API for Alasql, so it can be solved with separate plug-ins

**Comment by IPWright83** [comment]
A) I'd seriously consider just using someone else's effort and forking Squel.js to include in your library if licences match up.

**Comment by agershun** [comment]
Thank you for idea! I investigate integration with Sequel.js on the next week.

**Comment by mathiasrw** [comment]
Did you ever proceed with integrating with sequel?
